### ISSUE TITLE
Deno Deploy Example

### ISSUE THREAD

**Issue by alexlafroscia** [exhibitionist-digital/ultra-examples#11]
Hey there! I'm really interested in Ultra and have been wanting to check out Deno Deploy, so I tried to write up a basic site today and deploy it. I ran into a couple of issues that I figured I would mention:

- The GitHub Action configuration shows the "project name variable" in square brackets like this:
    ```yaml
     - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: [PROJECT_NAME]
          entrypoint: ULTRA.js
          root: .ultra
      ```
      It might just be me, but I took that to mean that the name of the project should be in square brackets, since that `[ ]` syntax represents a YAML array. Obviously that doesn't make sense now that I'm thinking about it, but when just quickly copy-and-pasting it was an easy mistake to make
- The example shows that the build step needs to happen with the `root` environment variable set, but as far as I can tell, the environment variable is actually needed at _runtime_ (I see it being read from in the generated `.ultra/deno/server.js` file). I had to go into Deno Deploy's configuration option to set that
- Once I did that, I could actually access the deployed site... but it doesn't seem to work at all. An exception gets thrown without any useful information (no message on the error, and the whole stack trace is minified functions that don't really make it possible to trace what went wrong
